### ISSUE TITLE
MacOS Ventura Support

### ISSUE THREAD

**Issue by M1Minecraft** [stackotter/delta-client#116]
Delta Client on MacOS Ventura keeps on saying "Pinging..." forever. 

No errors are actually shown, but Delta Client it only stuck on "Pinging", it also says "scanning LAN...".

Delta Client should be working on Monetery, but I think this problem only occurs on Ventura at the moment. 

<img width="892" alt="Screenshot 2022-06-22 at 10 52 32 PM" src="https://user-images.githubusercontent.com/88834989/175196944-e57569ae-6ef6-40a3-ab3e-2adda2d01b4d.png">

- OS: [MacOS Ventura Beta 2]
- Hardware: [M1 MacBook Pro 13 inch]
- Build: [v0.1.0-alpha.1]

**Comment by M1Minecraft** [comment]
I've built it, but it still says pinging, maybe it's a Ventura problem.

**Comment by gracien-app** [comment]
Fixed [here](https://github.com/stackotter/delta-client/pull/117#issue-1282875870)


You can check it out with ``gh pr checkout 117``

**Comment by stackotter** [comment]
Do either of you still get this issue on the latest Ventura beta (I don't have it installed so I can't check)

**Comment by stackotter** [comment]
How's it go on the public release of Ventura? (I haven't updated yet)

**Comment by stackotter** [comment]
I'm on the latest version of Ventura and this issue doesn't occur for me. I'll close this and if anyone experiences this again they can reopen the issue
